### ISSUE TITLE
spazzing copies

### ISSUE THREAD

**Issue by snovan** [IxLahiji/CMPT371Team3#103]
when multiple copies are clipping in the same spot they all go wild and start flashing.
replicate-able 100% of the time by making multiple copies from the tray and not moving them before making more

**Comment by mkp003** [comment]
This is a repeat of issue #46 where we have Copies instantiating in the same position.  Suggested Fix: since we likely won't have time to implement the "Observatory Grid" idea of having copies snap to specific locations around the user, it would be best to limit the number of Copies the user can create.  There should then be a check to see if the new image will have the same Transform.position.z as any other image in the Copy List.  If it does, change the the z position by -0.05 (moves towards the user) and check again.

**Comment by snovan** [comment]
see #46
