### ISSUE TITLE
AvatarSurfaceShaderSelfOccluding giving error in build

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#22]
the error is: 'OvrAvatar/AvatarSurfaceShaderSelfOccluding': Invalid const register num: 64. Max allowed is 31.  
This error is repeated numerous times in cloud build log #33.

**Comment by KyleS22** [comment]
We could try this method:
      Add the three shaders, AvatarSurfaceShader, AvatarSurfaceShaderPBS, AvatarSurfaceShaderSelfOccluding to Edit>Project Settings>Player>OtherSettings>Optimization>PreloadedAssets.

This may clear up the issue. There is more detail here https://forums.oculus.com/community/discussion/48199/avatar-surface-shader-errors

**Comment by KyleS22** [comment]
So because this failed, we can try this:

To fix this I added the following lines:

   #pragma exclude_renderers gles3 metal d3d11_9x xbox360 xboxone ps3 ps4 psp2
   #pragma target 3.0

 to the shader files:
  AvatarSurfaceShader.shader
  AvatarSurfaceShaderPBS.shader
  AvatarSurfaceShaderSelfOccluding.shader.

If you search for "pragma target 2.0" I saw there were 2 instances of this. SM 2.0 has a limit of 32 const registers, which would seem to explain the errors.

Also found here:  https://forums.oculus.com/community/discussion/48199/avatar-surface-shader-errors

**Comment by KyleS22** [comment]
Update on the issue, there is one file without the `#pragma 3.0`, so we added it.  Also added `#pragma glsl` as per another forum post recommendation.

**Comment by KyleS22** [comment]
Issue solved via the above comment
