### ISSUE TITLE
Images Occasionally lengthen or enlarge

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#66]
During user testing, the images seem to once in a while stretch when the user looks away.  Not sure how this occurring, but the images are likely interacting with something a warp (like the buttons used to do).

**Comment by oitoku** [comment]
This appears to have been resolved with issue #29.

**Comment by mkp003** [comment]
This still seems to be an issue when using Oculus #1, but not on the other one.

**Comment by snovan** [comment]
Issue was unable to be replicated. Regression tests cannot be written. We will watch closely for this issue during user testing. closing the issue for now.

**Comment by snovan** [comment]
it may have been a scale error that was occasionally triggering when objects were being transferred from one parent (the hand) to another (the workspace). Scale distortions could happen if you're setting the parent field directly instead of using the SetParent() method. This solution will be explored if the bug ever happens again
