### ISSUE TITLE
copies aren't deleting

### ISSUE THREAD

**Issue by BriKostur** [IxLahiji/CMPT371Team3#91]
currently copies are just set to inactive as opposed to being deleted on close

**Comment by KyleS22** [comment]
This issue has strong relations to issue #100 .

**Comment by IxLahiji** [comment]
This wasn't being changed to actually destroying copies, because of issues with "Destroy()" and "DestroyImmediate()". DestroyImmediate is to be called to delete an object in editor mode, and Destroy is called to delete an object while in a compiled build. 

The solution would be to check if the the program is in editor mode, using the flag "Application.isEditor". This can be made into a general function we can call "SafeDelete()" and could be applied to any GameObject

```if (Application.isEditor){
    DestroyImmediate(GameObject);
}
else{
   Destroy(GameObject);
}```

**Comment by herambsawant1** [comment]
Reviewed the code
