### ISSUE TITLE
Images randomly grow on hands

### ISSUE THREAD

**Issue by mkp003** [IxLahiji/CMPT371Team3#96]
This seems to occur only on Oculus #1.  Is repeatable when the user twists and looks away from an image.

**Comment by snovan** [comment]
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported in Unity 5.
If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "x-ray-skull-from-right-side/CopyOutline", Mesh asset path "Library/unity default resources" Mesh name "Quad"


This is the error message that pops up when it happens.
I believe this happens when the cameras noise causes the hands to glitch out and if that happens at the exact same time as the user lets go/ grabs an image that becomes a child of the hand, then the image glitches and is manipulated the same as its parent

**Comment by mkp003** [comment]
Please read the comment associated with issue #112 .  If i'm not mistaken, is the non-convex Mesh...... error a different issue altogether? I believe that issue was fixed by removing an unneeded mesh on either the hands or the copy prefab? Will tag as pending review for now, but let me know if the problem actually is persisting.

**Comment by EvanSnook** [comment]
we have confirmed that the bug is dependent on the single machine and Is no problem of our programs
